//! Generates `static/css/highlight.css` — the stylesheet matching the
//! CSS classes comrak's syntect adapter emits (ClassStyle::Spaced).
//!
//! Run once after changing the highlight theme:
//!
//! ```text
//! cargo run --example gen_highlight_css
//! ```

use syntect::highlighting::ThemeSet;
use syntect::html::{ClassStyle, css_for_theme_with_class_style};

const THEME: &str = "base16-eighties.dark";
const OUTPUT: &str = "static/css/highlight.css";

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let theme_set = ThemeSet::load_defaults();
    let theme = theme_set
        .themes
        .get(THEME)
        .ok_or_else(|| format!("theme {THEME} not found"))?;

    let css = css_for_theme_with_class_style(theme, ClassStyle::Spaced)?;
    let header = format!(
        "/* Generated by `cargo run --example gen_highlight_css` — theme: {THEME}. Do not edit by hand. */\n"
    );
    std::fs::write(OUTPUT, format!("{header}{css}"))?;
    println!("wrote {OUTPUT}");
    Ok(())
}
